language: julia
os:
    - linux
julia:
    - 0.6
notifications:
    email: false
after_success:
  - julia -e 'Pkg.add("Documenter"); Pkg.add("Coverage")'
  - julia -e 'cd(Pkg.dir("IRAM")); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'cd(Pkg.dir("IRAM")); include(joinpath("docs", "make.jl"))'